---
# openwrt-base: entry point for meta
galaxy_info:
  author: James Cuzella
  description: Installs python and Ansible dependencies via opkg on OpenWRT / LEDE
  company: LyraPhase
  license: MIT
  min_ansible_version: 2.5
  platforms:
  # Platforms tested are uncommented, but it probably works on most CentOS/RHEL
  platforms:
    - name: Openwrt
      versions:
        - 17.01
  #- name: EL
  #  versions:
  #     - all
  #     - 5
  #     - 6
  #     - 7
  # - name: GenericUNIX
  #   versions:
  #     - all
  #     - any
  # - name: Fedora
  #   versions:
  #     - all
  #     - 16
  #     - 17
  #     - 18
  #     - 19
  #     - 20
  # - name: opensuse
  #   versions:
  #     - all
  #     - 12.1
  #     - 12.2
  #     - 12.3
  #     - 13.1
  #     - 13.2
  # - name: Amazon
  #   versions:
  #     - all
  #     - 2013.03
  #     - 2013.09
  # - name: GenericBSD
  #   versions:
  #     - all
  #     - any
  # - name: FreeBSD
  #   versions:
  #     - all
  #     - 8.0
  #     - 8.1
  #     - 8.2
  #     - 8.3
  #     - 8.4
  #     - 9.0
  #     - 9.1
  #     - 9.1
  #     - 9.2
  # - name: Ubuntu
  #   versions:
  #     - all
  #     - lucid    # 10.04
  #     - precise  # 12.04
  #     - saucy    # 13.10
  #     - trusty   # 14.04
  #     - utopic   # 14.10
  # - name: SLES
  #   versions:
  #     - all
  #     - 10SP3
  #     - 10SP4
  #     - 11
  #     - 11SP1
  #     - 11SP2
  #     - 11SP3
  # - name: GenericLinux
  #   versions:
  #     - all
  #     - any
  # - name: Debian
  #   versions:
  #     - all
  #     - etch
  #     - lenny
  #     - squeeze
  #     - wheezy
  # - name: Darwin
  #   versions:
  #     - all
  galaxy_tags:
    - system
    - networking
    - openwrt
  categories:
  #   - web
    - system
    - packaging
  #   - networking
  #   - monitoring
  #   - development
  #   - database:sql
  #   - database:nosql
  #   - database
  #   - clustering
  #   - cloud:rax
  #   - cloud:gce
  #   - cloud:ec2
  #   - cloud
  dependencies:
  # Specify role dependencies here
  # For foo
  #  - foo
#version: 0.0.1 ## Ansible 2.0 broke this. Uncomment if / when they ever fix ansible/ansible#13496
